### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by rogermc2** [charlie5/cBound#1]
This looks like a very useful product but I can't figure out how to use it.
Can I use cBound to generate bindings for any c++ header file.
If so, how?

**Comment by charlie5** [comment]
The bindings are generated by a 'companion' project https://github.com/charlie5/swig4ada .

Swig4Ada handles C libs reasonably well and C++ libs to a lesser extent (depending on C++ features used).

It is still a (very slow) work in progress, although I'll be trying to spend more time on it soon.

**Comment by rogermc2** [comment]
Good to hear that you are still working on it.
I have only recently needed to write bindings for C++ and have run into difficulties in that the g++ binding generator doesn't generate bindings for all the C++ headers that I submit.
I will try swig4ada.

**Comment by rogermc2** [comment]
I tried to build swig4ada using`build_gnat_swig` but:
~~~
:/Applications_Packages/swig4ada Roger$./build_gnat_swig
swiggy.gpr:1:06: unknown project file: "gmp"
gprbuild: "swiggy" processing failed
~~~

**Comment by charlie5** [comment]
Hi again,

   The 'gmp' binding project is in cBound.

   Adding the lines to bashrc (or equiv) as mentioned in the cBound README should make it visible/available.

Regards.

**Comment by rogermc2** [comment]
I'm working on building swig4ada but am stuck with
 `private with GMP_lean.mpz_t;` in `gmp-discrete.ads` not found.
`gprbuild` fails with: `file "gmp_lean.ads" not found`
I cannot find  `gmp_lean.ads` anywhere.
